repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        additional_dependencies: ['toml']
        exclude: >
            (?x)^(
                templates/.*|
            )$

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        exclude: >
          (?x)^(
              templates/.*|
          )$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]
